// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3WIc6Ud9okHY2_M0nc-pi-_UhKdCly4o',
    appId: '1:878034188842:web:c22715b916931c12a7a153',
    messagingSenderId: '878034188842',
    projectId: 'academic-task-manager-a0cfe',
    authDomain: 'academic-task-manager-a0cfe.firebaseapp.com',
    storageBucket: 'academic-task-manager-a0cfe.firebasestorage.app',
    measurementId: 'G-YZ1S685V3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEAAq0K7D_GXqJzjiYT41wk-RmAR5pBO0',
    appId: '1:878034188842:android:bf019e2b60c9d66da7a153',
    messagingSenderId: '878034188842',
    projectId: 'academic-task-manager-a0cfe',
    storageBucket: 'academic-task-manager-a0cfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUwBoaAyiIpH7iyraH4zF9il6EUzgq8D0',
    appId: '1:878034188842:ios:59320508723e93a6a7a153',
    messagingSenderId: '878034188842',
    projectId: 'academic-task-manager-a0cfe',
    storageBucket: 'academic-task-manager-a0cfe.firebasestorage.app',
    iosBundleId: 'com.example.academicTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUwBoaAyiIpH7iyraH4zF9il6EUzgq8D0',
    appId: '1:878034188842:ios:59320508723e93a6a7a153',
    messagingSenderId: '878034188842',
    projectId: 'academic-task-manager-a0cfe',
    storageBucket: 'academic-task-manager-a0cfe.firebasestorage.app',
    iosBundleId: 'com.example.academicTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3WIc6Ud9okHY2_M0nc-pi-_UhKdCly4o',
    appId: '1:878034188842:web:e3e19e9cb2c86f23a7a153',
    messagingSenderId: '878034188842',
    projectId: 'academic-task-manager-a0cfe',
    authDomain: 'academic-task-manager-a0cfe.firebaseapp.com',
    storageBucket: 'academic-task-manager-a0cfe.firebasestorage.app',
    measurementId: 'G-THXWSQHTH4',
  );
}
